# Generated by Django 4.1.7 on 2023-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Modelflick', max_length=255),
        ),
    ]
